/*
 * LOGIN ACTIONS
 */
export const LOGIN_UPDATE_EMAIL = 'LOGIN_UPDATE_EMAIL';
export const LOGIN_UPDATE_PASSWORD = 'LOGIN_UPDATE_PASSWORD';
export const LOGIN_UPDATE_IS_ERROR = 'LOGIN_UPDATE_IS_ERROR';
/*
 * REGISTER ACTIONS
 */
export const REGISTER_UPDATE_INFORMATION = 'REGISTER_UPDATE_INFORMATION';
export const REGISTER_CLEAR_INFORMATION = 'REGISTER_CLEAR_INFORMATION';
export const REGISTER_UPDATE_IS_ERROR = 'REGISTER_UPDATE_IS_ERROR';
/*
 * SESSION ACTIONS
 */
export const SESSION_UPDATE = 'SESSION_UPDATE';
export const SESSION_DELETE = 'SESSION_DELETE';
export const SESSION_RECOVER = 'SESSION_RECOVER';
